name: Metrics
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Yehokhananlima
          template: classic
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata

          # Linguagens
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Hábitos de código
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Repositórios
          plugin_repositories: yes
          plugin_repositories_pinned: 6

          # Streak
          plugin_streak: yes

          # Notable contributions
          plugin_notable: yes
